/**
 * Export Utilities for Orchestra Coder
 * Handles file downloads and exports
 */

/**
 * Download file as text
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download multiple files as ZIP
 */
export async function downloadFilesAsZip(files: { [key: string]: string }, zipName: string) {
  try {
    const JSZip = (await import('jszip')).default;
    const zip = new JSZip();

    // Add files to zip
    Object.entries(files).forEach(([filename, content]) => {
      zip.file(filename, content);
    });

    // Generate zip and download
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${zipName}.zip`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Failed to create ZIP file:', error);
    // Fallback: download files individually
    Object.entries(files).forEach(([filename, content]) => {
      downloadFile(content, filename);
    });
  }
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Generate code snippet for embedding
 */
export function generateEmbedCode(projectId: string): string {
  return `<iframe src="https://orchestra-coder.example.com/embed/${projectId}" width="100%" height="600" frameborder="0"></iframe>`;
}

/**
 * Generate markdown documentation
 */
export function generateMarkdownDoc(
  title: string,
  description: string,
  results: { [key: string]: string }
): string {
  return `# ${title}

## Description
${description}

## Frontend Component
\`\`\`tsx
${results.frontend}
\`\`\`

## Backend API
\`\`\`typescript
${results.backend}
\`\`\`

## DevOps Configuration
\`\`\`yaml
${results.devops}
\`\`\`

## Database Schema
\`\`\`sql
${results.database}
\`\`\`

---
Generated by Orchestra Coder
`;
}

/**
 * Generate HTML documentation
 */
export function generateHTMLDoc(
  title: string,
  description: string,
  results: { [key: string]: string }
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    h1, h2 { color: #0066ff; }
    pre {
      background: #f0f0f0;
      padding: 15px;
      border-radius: 5px;
      overflow-x: auto;
      border-left: 4px solid #0066ff;
    }
    code {
      font-family: 'Monaco', 'Courier New', monospace;
      font-size: 14px;
    }
    .section {
      background: white;
      padding: 20px;
      margin: 20px 0;
      border-radius: 5px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p>${description}</p>

  <div class="section">
    <h2>Frontend Component</h2>
    <pre><code>${escapeHtml(results.frontend)}</code></pre>
  </div>

  <div class="section">
    <h2>Backend API</h2>
    <pre><code>${escapeHtml(results.backend)}</code></pre>
  </div>

  <div class="section">
    <h2>DevOps Configuration</h2>
    <pre><code>${escapeHtml(results.devops)}</code></pre>
  </div>

  <div class="section">
    <h2>Database Schema</h2>
    <pre><code>${escapeHtml(results.database)}</code></pre>
  </div>

  <footer style="text-align: center; margin-top: 40px; color: #999; font-size: 12px;">
    Generated by Orchestra Coder
  </footer>
</body>
</html>`;
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}

/**
 * Generate package.json for the project
 */
export function generatePackageJson(
  projectTitle: string,
  dependencies: string[] = []
): string {
  const packageJson = {
    name: projectTitle.toLowerCase().replace(/\s+/g, '-'),
    version: '1.0.0',
    description: projectTitle,
    main: 'dist/index.js',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
      test: 'vitest',
      lint: 'eslint src --ext ts,tsx'
    },
    dependencies: {
      react: '^19.0.0',
      'react-dom': '^19.0.0',
      express: '^4.18.0',
      ...Object.fromEntries(dependencies.map(dep => [dep, 'latest']))
    },
    devDependencies: {
      typescript: '^5.0.0',
      vite: '^5.0.0',
      '@vitejs/plugin-react': '^4.0.0'
    }
  };

  return JSON.stringify(packageJson, null, 2);
}
